// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/proto/product_service.proto

package com_gbusiness_product_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProductsDisplayRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsDisplayRequest) Reset()         { *m = GetProductsDisplayRequest{} }
func (m *GetProductsDisplayRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsDisplayRequest) ProtoMessage()    {}
func (*GetProductsDisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5034c5e437523871, []int{0}
}

func (m *GetProductsDisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsDisplayRequest.Unmarshal(m, b)
}
func (m *GetProductsDisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsDisplayRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsDisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsDisplayRequest.Merge(m, src)
}
func (m *GetProductsDisplayRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsDisplayRequest.Size(m)
}
func (m *GetProductsDisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsDisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsDisplayRequest proto.InternalMessageInfo

// Response for GetProductsDisplayRequest.
type GetProductsDisplayResponse struct {
	// List of retrieved products.
	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	// List of retrieved product topics.
	ProductTopics []*ProductTopic `protobuf:"bytes,2,rep,name=product_topics,json=productTopics,proto3" json:"product_topics,omitempty"`
	// List of retrieved topic's categories.
	TopicCategories      []*TopicCategory `protobuf:"bytes,3,rep,name=topic_categories,json=topicCategories,proto3" json:"topic_categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetProductsDisplayResponse) Reset()         { *m = GetProductsDisplayResponse{} }
func (m *GetProductsDisplayResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsDisplayResponse) ProtoMessage()    {}
func (*GetProductsDisplayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5034c5e437523871, []int{1}
}

func (m *GetProductsDisplayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsDisplayResponse.Unmarshal(m, b)
}
func (m *GetProductsDisplayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsDisplayResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsDisplayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsDisplayResponse.Merge(m, src)
}
func (m *GetProductsDisplayResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsDisplayResponse.Size(m)
}
func (m *GetProductsDisplayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsDisplayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsDisplayResponse proto.InternalMessageInfo

func (m *GetProductsDisplayResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *GetProductsDisplayResponse) GetProductTopics() []*ProductTopic {
	if m != nil {
		return m.ProductTopics
	}
	return nil
}

func (m *GetProductsDisplayResponse) GetTopicCategories() []*TopicCategory {
	if m != nil {
		return m.TopicCategories
	}
	return nil
}

// Definition of a product
type Product struct {
	// Unique identifier for a product with following format:
	// "product/[uid]"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title of the product.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Short description of the product.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// List of topic ids that represent the product.
	TopicIds             []string `protobuf:"bytes,4,rep,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5034c5e437523871, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetTopicIds() []string {
	if m != nil {
		return m.TopicIds
	}
	return nil
}

// Definition of a product's topic
type ProductTopic struct {
	// Unique identifier for a topic with following format:
	// "topic/[uid]"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique id of the category this topic belongs to.
	CategoryId string `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Short description of the topic.
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductTopic) Reset()         { *m = ProductTopic{} }
func (m *ProductTopic) String() string { return proto.CompactTextString(m) }
func (*ProductTopic) ProtoMessage()    {}
func (*ProductTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_5034c5e437523871, []int{3}
}

func (m *ProductTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductTopic.Unmarshal(m, b)
}
func (m *ProductTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductTopic.Marshal(b, m, deterministic)
}
func (m *ProductTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductTopic.Merge(m, src)
}
func (m *ProductTopic) XXX_Size() int {
	return xxx_messageInfo_ProductTopic.Size(m)
}
func (m *ProductTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductTopic.DiscardUnknown(m)
}

var xxx_messageInfo_ProductTopic proto.InternalMessageInfo

func (m *ProductTopic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductTopic) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *ProductTopic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type TopicCategory struct {
	// Unique identifier for a category with following format:
	// "category/[uid]"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short description of the category.
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicCategory) Reset()         { *m = TopicCategory{} }
func (m *TopicCategory) String() string { return proto.CompactTextString(m) }
func (*TopicCategory) ProtoMessage()    {}
func (*TopicCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_5034c5e437523871, []int{4}
}

func (m *TopicCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicCategory.Unmarshal(m, b)
}
func (m *TopicCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicCategory.Marshal(b, m, deterministic)
}
func (m *TopicCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicCategory.Merge(m, src)
}
func (m *TopicCategory) XXX_Size() int {
	return xxx_messageInfo_TopicCategory.Size(m)
}
func (m *TopicCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicCategory.DiscardUnknown(m)
}

var xxx_messageInfo_TopicCategory proto.InternalMessageInfo

func (m *TopicCategory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TopicCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProductsDisplayRequest)(nil), "com.gbusiness.agentslot.api.GetProductsDisplayRequest")
	proto.RegisterType((*GetProductsDisplayResponse)(nil), "com.gbusiness.agentslot.api.GetProductsDisplayResponse")
	proto.RegisterType((*Product)(nil), "com.gbusiness.agentslot.api.Product")
	proto.RegisterType((*ProductTopic)(nil), "com.gbusiness.agentslot.api.ProductTopic")
	proto.RegisterType((*TopicCategory)(nil), "com.gbusiness.agentslot.api.TopicCategory")
}

func init() {
	proto.RegisterFile("src/main/proto/product_service.proto", fileDescriptor_5034c5e437523871)
}

var fileDescriptor_5034c5e437523871 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x24, 0xef, 0x9f, 0x76, 0xfa, 0xb6, 0xca, 0xea, 0x21, 0x6d, 0x0f, 0x86, 0x20,
	0x98, 0x53, 0x0a, 0x55, 0xaf, 0x82, 0x55, 0x90, 0x5e, 0xa4, 0xa4, 0xde, 0x4b, 0x9a, 0x5d, 0xca,
	0x40, 0x9b, 0xac, 0x99, 0xad, 0xd0, 0xa3, 0xf8, 0x1d, 0xfc, 0xbc, 0xd2, 0xcd, 0x56, 0x52, 0x63,
	0x5b, 0xbc, 0x04, 0xe6, 0xd9, 0x9d, 0xdf, 0x33, 0x13, 0x9e, 0x85, 0x73, 0xca, 0x93, 0xde, 0x22,
	0xc6, 0xb4, 0x27, 0xf3, 0x4c, 0x65, 0xeb, 0x2f, 0x5f, 0x26, 0x6a, 0x42, 0x22, 0x7f, 0xc1, 0x44,
	0x84, 0x5a, 0x65, 0xed, 0x24, 0x5b, 0x84, 0xb3, 0xe9, 0x92, 0x30, 0x15, 0x44, 0xa1, 0xb9, 0x14,
	0xc6, 0x12, 0xfd, 0x2e, 0xb4, 0x1f, 0x84, 0x1a, 0x15, 0x0a, 0xdd, 0x23, 0xc9, 0x79, 0xbc, 0x8a,
	0xc4, 0xf3, 0x52, 0x90, 0xf2, 0x5f, 0x6d, 0xe8, 0x7c, 0x77, 0x4a, 0x32, 0x4b, 0x49, 0xb0, 0x1b,
	0xa8, 0x19, 0x14, 0xb9, 0x96, 0xe7, 0x04, 0x8d, 0xbe, 0x1f, 0xee, 0x74, 0x0a, 0x0d, 0x25, 0xfa,
	0xec, 0x61, 0x8f, 0xd0, 0xda, 0xcc, 0xab, 0x32, 0x89, 0x09, 0xb9, 0xb6, 0xa6, 0x5c, 0x1c, 0xa6,
	0x3c, 0xad, 0xef, 0x47, 0x4d, 0x59, 0xaa, 0x88, 0x8d, 0xe1, 0x58, 0x73, 0x26, 0x49, 0xac, 0xc4,
	0x2c, 0xcb, 0x51, 0x90, 0xeb, 0x68, 0x62, 0xb0, 0x87, 0xa8, 0x9b, 0xef, 0x8a, 0x8e, 0x55, 0x74,
	0xa4, 0x4a, 0x25, 0x0a, 0xf2, 0x53, 0xf8, 0x67, 0x3c, 0x59, 0x0b, 0x6c, 0xe4, 0xae, 0xe5, 0x59,
	0x41, 0x3d, 0xb2, 0x91, 0xb3, 0x53, 0xf8, 0xa3, 0x50, 0xcd, 0x85, 0x6b, 0x6b, 0xa9, 0x28, 0x98,
	0x07, 0x0d, 0x2e, 0x28, 0xc9, 0x51, 0x2a, 0xcc, 0x52, 0xd7, 0xd1, 0x67, 0x65, 0x89, 0x75, 0xa1,
	0x5e, 0xcc, 0x89, 0x9c, 0xdc, 0xdf, 0x9e, 0x13, 0xd4, 0xa3, 0x9a, 0x16, 0x86, 0x9c, 0xfc, 0x18,
	0xfe, 0x97, 0x77, 0xac, 0x98, 0x9e, 0x41, 0xc3, 0xac, 0xb7, 0x9a, 0x20, 0x37, 0xd6, 0xb0, 0x91,
	0x86, 0xfc, 0xb0, 0xbf, 0x7f, 0x0b, 0xcd, 0xad, 0xa5, 0x2b, 0x1e, 0x5f, 0x10, 0x76, 0x05, 0xd1,
	0x7f, 0xb7, 0xa0, 0x65, 0xc6, 0x1c, 0x17, 0x51, 0x63, 0x6f, 0x16, 0xb0, 0x6a, 0x58, 0xd8, 0xd5,
	0x9e, 0x5f, 0xbf, 0x33, 0x79, 0x9d, 0xeb, 0x1f, 0x76, 0x15, 0x89, 0xf4, 0x7f, 0x0d, 0xfa, 0xb0,
	0x3b, 0xec, 0x83, 0x93, 0xed, 0x91, 0x47, 0xeb, 0xc7, 0x31, 0xb2, 0xa6, 0x7f, 0xf5, 0x2b, 0xb9,
	0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0x78, 0xe1, 0x72, 0xeb, 0x4d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProductsDisplay(ctx context.Context, in *GetProductsDisplayRequest, opts ...grpc.CallOption) (*GetProductsDisplayResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductsDisplay(ctx context.Context, in *GetProductsDisplayRequest, opts ...grpc.CallOption) (*GetProductsDisplayResponse, error) {
	out := new(GetProductsDisplayResponse)
	err := c.cc.Invoke(ctx, "/com.gbusiness.agentslot.api.ProductService/GetProductsDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	GetProductsDisplay(context.Context, *GetProductsDisplayRequest) (*GetProductsDisplayResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) GetProductsDisplay(ctx context.Context, req *GetProductsDisplayRequest) (*GetProductsDisplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsDisplay not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProductsDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductsDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.gbusiness.agentslot.api.ProductService/GetProductsDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductsDisplay(ctx, req.(*GetProductsDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.gbusiness.agentslot.api.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductsDisplay",
			Handler:    _ProductService_GetProductsDisplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/product_service.proto",
}
